### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by DonJayamanne** [dwyl/learn-ngrok#2]

**Comment by nelsonic** [comment]
@DonJayamanne did you _mean_ to open 4 empty "Hello" issues?
![image](https://user-images.githubusercontent.com/194400/49211215-f7b17600-f3b6-11e8-9027-72510c45d553.png)

Are you testing something?

**Comment by DonJayamanne** [comment]
Sorry, I thought I was creating this on my own repo. No wonder they didn't appear. Lol

**Comment by DonJayamanne** [comment]
Yes, testing on my own private repos, but had opened this accidentally. 
Rookie mistake, need to close some of my tabs.

**Comment by nelsonic** [comment]
@DonJayamanne too many tabs. we feel you. 👍 
Hope you're having a good day. ☀️
