### ISSUE TITLE
Use the same authtoken for more than one user

### ISSUE THREAD

**Issue by japostigo-km** [dwyl/learn-ngrok#6]
I know each user should have its own authtoken. But do you know if is it possible having, for example, two users using the same ngrok auth token at the same time?

**Comment by nelsonic** [comment]
@japostigo-atsistemas we have never tried to share auth tokens ... 🤔 
@inconshreveable the creator of `ngrok` will probably be able to help you a lot faster. 💡 
Please open an issue on: https://github.com/inconshreveable/ngrok/issues 📥 
Thanks! 🌻

**Comment by nelsonic** [comment]
Closing as not updated in a `while` ... ✅
