### ISSUE TITLE
Can,t access to other device ngrok link using zphisher

### ISSUE THREAD

**Issue by MAXENDkkj** [dwyl/learn-ngrok#7]
It gives link but my problem is it cant open in other device.  The page is blank white screen

**Comment by MAXENDkkj** [comment]
https://user-images.githubusercontent.com/94516360/142154144-42a87953-dbb0-4587-a7c3-ede29a444984.mp4

**Comment by nelsonic** [comment]
This should have been reported on the `ngrok` forum. 💭 
Closing as we cannot fix it. ✅
